# CI pipeline for building the front-end, and deploying it through scp

kind: pipeline
name: datascience-front-end

steps:
- name: build
  image: node
  commands:
  - touch test
  # - npm install
  # - npm run build
  when:
    branch:
    - master
    
- name: scp
  image: appleboy/drone-scp
  settings:
    host: www.datascience.lays.pro
    username: ubuntu
    target: ${TARGET_PATH}
    source: test
     #./build
  environment:
    SSH_KEY:
      from_secret: SERVER_KEY
    TARGET_PATH:
      from_secrets: TARGET_PATH
  when:
    branch:
    - master