# CI pipeline for building the front-end at datascience.lays.pro, and deploying it with scp

kind: pipeline
name: datascience-front-end

steps:
- name: build
  image: node
  commands:
  - npm install
  - npm run build
  when:
    branch:
    - master
    
- name: deploy_scp
  image: appleboy/drone-scp
  settings:
    host: www.datascience.lays.pro
    username: ubuntu
    target: ~/
    source: ./build
  environment:
    SSH_KEY:
      from_secret: SERVER_KEY
    TARGET_PATH:
      from_secrets: TARGET_PATH
  when:
    branch:
    - master